[package]
name = "chronicle"
edition = "2024.beta"
version = "0.1.0"
authors = ["ConsssLabs"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
chronicle = "0x0"

[dev-dependencies]

[dev-addresses]
