#[test_only]
module chronicle::chronicle_tests;

use sui::test_scenario as ts;
use sui::clock::{Self, Clock};
use chronicle::chronicle::{Self, ChronicleRegistry, AdminCap};

// Force a given per-battle rank, mint via the test bypass, assert tier+order.
#[test_only]
fun check(
    reg: &mut ChronicleRegistry,
    clk: &Clock,
    battle: u8,
    rank: u64,
    hp: u8,
    expect_tier: u8,
    ctx: &mut TxContext,
) {
    chronicle::set_count_for_testing(reg, battle, rank - 1);
    let nft = chronicle::mint_for_testing(reg, battle, 1, hp, b"blob_id_x", clk, ctx);
    assert!(chronicle::mint_order(&nft) == rank, 100 + rank);
    assert!(chronicle::tier(&nft) == expect_tier, rank);
    chronicle::destroy_for_testing(nft);
}

// Cross-language voucher byte-layout lock. The expected vector is generated by
// the backend signer (play/functions/[[path]].js buildVoucherMessage) for the
// fixed inputs below; this asserts the on-chain message is byte-identical, so a
// signature the server makes will verify on-chain. If either side changes the
// layout, this test fails. Inputs: registry=0x7, player=0xab, battle=2, hero=5,
// hp=80, nonce=1, expiry=1000.
#[test]
fun voucher_message_byte_layout() {
    let msg = chronicle::build_voucher_message_for_testing(@0x7, @0xab, 2, 5, 80, 1, 1000);
    let expected = vector[67u8, 111u8, 110u8, 83u8, 83u8, 83u8, 87u8, 97u8, 114u8, 115u8, 47u8, 99u8, 104u8, 114u8, 111u8, 110u8, 105u8, 99u8, 108u8, 101u8, 45u8, 118u8, 111u8, 117u8, 99u8, 104u8, 101u8, 114u8, 47u8, 118u8, 49u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 7u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 171u8, 2u8, 5u8, 80u8, 1u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 232u8, 3u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8];
    assert!(msg == expected, 0);
}

// All rows from the design table (image2): floor by rank, +1 if hp>=80.
// tier: 0=Normal, 1=Bronze, 2=Silver, 3=Gold.
#[test]
fun tier_table_matches_design() {
    let mut sc = ts::begin(@0xA);
    chronicle::init_for_testing(ts::ctx(&mut sc));
    ts::next_tx(&mut sc, @0xA);
    let mut reg = ts::take_shared<ChronicleRegistry>(&sc);
    let clk = clock::create_for_testing(ts::ctx(&mut sc));

    check(&mut reg, &clk, 1, 3,    68,  2, ts::ctx(&mut sc)); // #3    68% -> Silver
    check(&mut reg, &clk, 1, 3,    85,  3, ts::ctx(&mut sc)); // #3    85% -> Gold
    check(&mut reg, &clk, 1, 120,  70,  1, ts::ctx(&mut sc)); // #120  70% -> Bronze
    check(&mut reg, &clk, 1, 120,  90,  2, ts::ctx(&mut sc)); // #120  90% -> Silver
    check(&mut reg, &clk, 1, 600,  95,  1, ts::ctx(&mut sc)); // #600  95% -> Bronze
    check(&mut reg, &clk, 1, 600,  40,  0, ts::ctx(&mut sc)); // #600  40% -> Normal
    check(&mut reg, &clk, 1, 1000, 100, 1, ts::ctx(&mut sc)); // #1000 100% -> Bronze (cap)
    check(&mut reg, &clk, 1, 100,  79,  2, ts::ctx(&mut sc)); // #100  79% -> Silver (floor, below threshold)
    check(&mut reg, &clk, 1, 101,  80,  2, ts::ctx(&mut sc)); // #101  80% -> Silver (bronze floor + upgrade)

    clock::destroy_for_testing(clk);
    ts::return_shared(reg);
    ts::end(sc);
}

// Per-battle rank: each battle has its own counter.
#[test]
fun first_chronicler_per_battle() {
    let mut sc = ts::begin(@0xA);
    chronicle::init_for_testing(ts::ctx(&mut sc));
    ts::next_tx(&mut sc, @0xA);
    let mut reg = ts::take_shared<ChronicleRegistry>(&sc);
    let clk = clock::create_for_testing(ts::ctx(&mut sc));

    let a = chronicle::mint_for_testing(&mut reg, 1, 1, 50, b"b", &clk, ts::ctx(&mut sc));
    let b = chronicle::mint_for_testing(&mut reg, 2, 1, 50, b"b", &clk, ts::ctx(&mut sc));
    assert!(chronicle::mint_order(&a) == 1 && chronicle::is_first_chronicler(&a), 1);
    assert!(chronicle::mint_order(&b) == 1 && chronicle::is_first_chronicler(&b), 2);
    chronicle::destroy_for_testing(a);
    chronicle::destroy_for_testing(b);

    clock::destroy_for_testing(clk);
    ts::return_shared(reg);
    ts::end(sc);
}

// #1001+ get no NFT — mint aborts with ENoNFT.
#[test]
#[expected_failure]
fun rank_over_max_aborts() {
    let mut sc = ts::begin(@0xA);
    chronicle::init_for_testing(ts::ctx(&mut sc));
    ts::next_tx(&mut sc, @0xA);
    let mut reg = ts::take_shared<ChronicleRegistry>(&sc);
    let clk = clock::create_for_testing(ts::ctx(&mut sc));

    chronicle::set_count_for_testing(&mut reg, 1, 1000); // next would be #1001
    let nft = chronicle::mint_for_testing(&mut reg, 1, 1, 100, b"b", &clk, ts::ctx(&mut sc));
    chronicle::destroy_for_testing(nft); // unreachable

    clock::destroy_for_testing(clk);
    ts::return_shared(reg);
    ts::end(sc);
}

// Fresh registry: version == 1, not paused; AdminCap can pause.
#[test]
fun version_gate_defaults_and_pause() {
    let mut sc = ts::begin(@0xA);
    chronicle::init_for_testing(ts::ctx(&mut sc));
    ts::next_tx(&mut sc, @0xA);
    let mut reg = ts::take_shared<ChronicleRegistry>(&sc);
    let admin = ts::take_from_sender<AdminCap>(&sc);
    assert!(chronicle::version(&reg) == 1, 1);
    assert!(!chronicle::is_paused(&reg), 2);
    chronicle::set_paused(&admin, &mut reg, true);
    assert!(chronicle::is_paused(&reg), 3);
    chronicle::set_paused(&admin, &mut reg, false);
    assert!(!chronicle::is_paused(&reg), 4);
    ts::return_to_sender(&sc, admin);
    ts::return_shared(reg);
    ts::end(sc);
}

// migrate on a current-version registry aborts (nothing to migrate).
#[test]
#[expected_failure]
fun migrate_on_current_aborts() {
    let mut sc = ts::begin(@0xA);
    chronicle::init_for_testing(ts::ctx(&mut sc));
    ts::next_tx(&mut sc, @0xA);
    let mut reg = ts::take_shared<ChronicleRegistry>(&sc);
    let admin = ts::take_from_sender<AdminCap>(&sc);
    chronicle::migrate(&admin, &mut reg); // version already == VERSION -> abort
    ts::return_to_sender(&sc, admin);
    ts::return_shared(reg);
    ts::end(sc);
}

// Paused registry blocks the real mint entry (aborts at the version/pause gate).
#[test]
#[expected_failure]
fun paused_blocks_mint() {
    let mut sc = ts::begin(@0xA);
    chronicle::init_for_testing(ts::ctx(&mut sc));
    ts::next_tx(&mut sc, @0xA);
    let mut reg = ts::take_shared<ChronicleRegistry>(&sc);
    let admin = ts::take_from_sender<AdminCap>(&sc);
    let clk = clock::create_for_testing(ts::ctx(&mut sc));
    chronicle::set_paused(&admin, &mut reg, true);
    // assert_active runs first, so dummy voucher args never get inspected.
    chronicle::mint_chronicle(&mut reg, 1, 1, b"t", b"", 50, b"b", 0, 9999999999999, b"x", &clk, ts::ctx(&mut sc));
    clock::destroy_for_testing(clk);
    ts::return_to_sender(&sc, admin);
    ts::return_shared(reg);
    ts::end(sc);
}
